version: '3'

volumes:
  internship-data:

services:
  app:
    container_name: internship_springboot
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/internship
      SPRING_DATASOURSE_PASSWORD: postgres
      SPRING_DATASOURSE_USERNAME: postgres
    restart: always
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - internship-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=internship
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always