spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    initialization-mode: always
    data:
      - 'classpath:db/changelog/v.0.1/sql-import/import-form.sql'
      - 'classpath:db/changelog/v.0.3/sql-import/import-internship.sql'
      - 'classpath:db/changelog/v.0.3/sql-import/import-user.sql'
      - 'classpath:db/changelog/v.0.3/sql-import/import-user-skill.sql'
      - 'classpath:db/changelog/v.0.3/sql-import/import-internship-skill.sql'
      - 'classpath:db/changelog/v.0.2/sql-import/import-interview.sql'
      - 'classpath:db/changelog/v.0.2/sql-import/import-interview-dates.sql'
      - 'classpath:db/changelog/v.0.2/sql-import/import-form-add-columns.sql'
      - 'classpath:db/changelog/v.0.3/sql-import/import-time-for-call.sql'
      - 'classpath:db/changelog/v.0.4/sql-import/country.sql'
      - 'classpath:db/changelog/v.0.4/sql-import/city.sql'


server:
  servlet:
    context-path: /api

file:
  path: "files"